/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package annuaire.panels;

import annuaire.Main;
import annuaire.Utils.Recuperer;
import annuaire.menus.TypeOne;
import annuaire.menus.TypeTwo;
import annuaire.personnes.Admin;
import annuaire.personnes.Student;
import annuaire.personnes.User;
import java.awt.GridLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.NoSuchElementException;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mosco
 */
public class Annuaire extends javax.swing.JPanel implements Runnable{
    
    private final GridLayout gridLayout = new GridLayout(0, 4, 5, 10);
    private TreeSet treeSet = new TreeSet();
    private final String table;
    /**
     * Creates new form Annuaire
     * @param users
     */
    public Annuaire(TreeSet<User> users) throws NoSuchElementException{
        initComponents();
        table = users.first().getClass().getSimpleName();
        jPanel.setLayout(gridLayout);
        
        makCard(users);
        setVisible(true);
        revalidate();
    }
    
    
    @Override
    public void run() {
        if(Main.admin == null){
            Main.setjMenuBar(new TypeOne());            
        }
        else{
            Main.setjMenuBar(new TypeTwo());
        }

        jPanel.revalidate();
        revalidate();
        System.err.println("je suis en cours ...");    
    }
    
    
    
    private void makCard(TreeSet<User> users){
        jPanel.removeAll();
        for(User user: users){
            jPanel.add(new Card(user));
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        str_recherche = new javax.swing.JTextField();
        btn_recherche = new javax.swing.JButton();
        btn_z = new javax.swing.JButton();
        btn_m = new javax.swing.JButton();
        btn_e = new javax.swing.JButton();
        btn_f = new javax.swing.JButton();
        btn_g = new javax.swing.JButton();
        btn_h = new javax.swing.JButton();
        btn_i = new javax.swing.JButton();
        btn_j = new javax.swing.JButton();
        btn_k = new javax.swing.JButton();
        btn_l = new javax.swing.JButton();
        btn_n = new javax.swing.JButton();
        btn_o = new javax.swing.JButton();
        btn_p = new javax.swing.JButton();
        btn_q = new javax.swing.JButton();
        btn_r = new javax.swing.JButton();
        btn_s = new javax.swing.JButton();
        btn_t = new javax.swing.JButton();
        btn_u = new javax.swing.JButton();
        btn_v = new javax.swing.JButton();
        btn_w = new javax.swing.JButton();
        btn_x = new javax.swing.JButton();
        btn_b = new javax.swing.JButton();
        btn_y = new javax.swing.JButton();
        btn_c = new javax.swing.JButton();
        actualiser = new javax.swing.JButton();
        rechercheCible = new javax.swing.JButton();
        btn_d = new javax.swing.JButton();
        btn_a = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(761, 565));

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel);

        jLabel2.setText("design by");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Groupe x");

        btn_recherche.setText("rechercher");
        btn_recherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_rechercheMouseClicked(evt);
            }
        });
        btn_recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rechercheActionPerformed(evt);
            }
        });

        btn_z.setText("Z");
        btn_z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_zMouseClicked(evt);
            }
        });

        btn_m.setText("M");
        btn_m.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mMouseClicked(evt);
            }
        });

        btn_e.setText("E");
        btn_e.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eMouseClicked(evt);
            }
        });

        btn_f.setText("F");
        btn_f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_fMouseClicked(evt);
            }
        });

        btn_g.setText("G");
        btn_g.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_gMouseClicked(evt);
            }
        });

        btn_h.setText("H");
        btn_h.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hMouseClicked(evt);
            }
        });

        btn_i.setText("I");
        btn_i.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_iMouseClicked(evt);
            }
        });

        btn_j.setText("J");
        btn_j.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_jMouseClicked(evt);
            }
        });

        btn_k.setText("K");
        btn_k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kMouseClicked(evt);
            }
        });

        btn_l.setText("L");
        btn_l.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lMouseClicked(evt);
            }
        });

        btn_n.setText("N");
        btn_n.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nMouseClicked(evt);
            }
        });

        btn_o.setText("O");
        btn_o.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_oMouseClicked(evt);
            }
        });

        btn_p.setText("P");
        btn_p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pMouseClicked(evt);
            }
        });

        btn_q.setText("Q");
        btn_q.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_qMouseClicked(evt);
            }
        });

        btn_r.setText("R");
        btn_r.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_rMouseClicked(evt);
            }
        });

        btn_s.setText("S");
        btn_s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sMouseClicked(evt);
            }
        });

        btn_t.setText("T");
        btn_t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tMouseClicked(evt);
            }
        });

        btn_u.setText("U");
        btn_u.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_uMouseClicked(evt);
            }
        });

        btn_v.setText("V");
        btn_v.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vMouseClicked(evt);
            }
        });

        btn_w.setText("W");
        btn_w.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_wMouseClicked(evt);
            }
        });

        btn_x.setText("X");
        btn_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xMouseClicked(evt);
            }
        });

        btn_b.setText("B");
        btn_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bMouseClicked(evt);
            }
        });

        btn_y.setText("Y");
        btn_y.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_yMouseClicked(evt);
            }
        });

        btn_c.setText("C");
        btn_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cMouseClicked(evt);
            }
        });

        actualiser.setText("Actualiser");
        actualiser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualiserMouseClicked(evt);
            }
        });

        rechercheCible.setBackground(java.awt.Color.orange);
        rechercheCible.setText("Recherche ciblée");
        rechercheCible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rechercheCibleMouseClicked(evt);
            }
        });

        btn_d.setText("D");
        btn_d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dMouseClicked(evt);
            }
        });

        btn_a.setText("A");
        btn_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btn_a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_b)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_d)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_e)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_f)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_g)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_h)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_i)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_j))
                    .addComponent(str_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_k)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_l)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_m)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_n)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_o)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_p)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_q)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_r)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_s)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_t)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_u)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_v)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_w)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_x)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_y)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_z)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rechercheCible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_recherche)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(actualiser)))
                        .addGap(159, 159, 159))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(99, 99, 99)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rechercheCible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(str_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_recherche)
                    .addComponent(actualiser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_b)
                    .addComponent(btn_c)
                    .addComponent(btn_e)
                    .addComponent(btn_f)
                    .addComponent(btn_g)
                    .addComponent(btn_h)
                    .addComponent(btn_i)
                    .addComponent(btn_j)
                    .addComponent(btn_k)
                    .addComponent(btn_l)
                    .addComponent(btn_n)
                    .addComponent(btn_o)
                    .addComponent(btn_p)
                    .addComponent(btn_q)
                    .addComponent(btn_r)
                    .addComponent(btn_s)
                    .addComponent(btn_t)
                    .addComponent(btn_u)
                    .addComponent(btn_v)
                    .addComponent(btn_w)
                    .addComponent(btn_x)
                    .addComponent(btn_y)
                    .addComponent(btn_z)
                    .addComponent(btn_m)
                    .addComponent(btn_d)
                    .addComponent(btn_a)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_rechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rechercheMouseClicked
       //Recuperer.recherche(database, table, list,str_recherche.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_rechercheMouseClicked

    private void btn_zMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_zMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_z.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_zMouseClicked

    private void btn_mMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_m.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_mMouseClicked

    private void btn_eMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_e.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_eMouseClicked

    private void btn_fMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_f.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_fMouseClicked

    private void btn_gMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_gMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_g.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_gMouseClicked

    private void btn_hMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_h.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_hMouseClicked

    private void btn_iMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_iMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_i.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_iMouseClicked

    private void btn_jMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_j.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_jMouseClicked

    private void btn_kMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_k.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_kMouseClicked

    private void btn_lMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_l.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_lMouseClicked

    private void btn_nMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_n.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_nMouseClicked

    private void btn_oMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_oMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_o.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_oMouseClicked

    private void btn_pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_p.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_pMouseClicked

    private void btn_qMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_qMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_q.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_qMouseClicked

    private void btn_rMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_r.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_rMouseClicked

    private void btn_sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_s.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_sMouseClicked

    private void btn_tMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_t.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_tMouseClicked

    private void btn_uMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_uMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_u.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_uMouseClicked

    private void btn_vMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_v.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_vMouseClicked

    private void btn_wMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_wMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_w.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_wMouseClicked

    private void btn_xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_x.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_xMouseClicked

    private void btn_bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_b.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_bMouseClicked

    private void btn_yMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_y.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_yMouseClicked

    private void btn_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_c.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_cMouseClicked

    private void rechercheCibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechercheCibleMouseClicked
        if(table.equals(Admin.class.getSimpleName()))
            Main.addToPaneG(new PanelAdmin("Rechercher"));
        else
            Main.addToPaneG(new PanelStudent("Rechercher"));
        
    }//GEN-LAST:event_rechercheCibleMouseClicked

    private void btn_dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_d.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_dMouseClicked

    private void actualiserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualiserMouseClicked
        treeSet.clear();
        ResultSet resultSet = Main.database.getAll(table);
        try {
            if(table.equals(Student.class.getSimpleName()))
                treeSet = Recuperer.etudiants(resultSet);
            else
                treeSet = Recuperer.admins(resultSet);
            
        } catch (SQLException ex) {
            Logger.getLogger(Annuaire.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_actualiserMouseClicked

    private void btn_aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aMouseClicked
        treeSet = Recuperer.rechercheSimple(table, btn_a.getText());
        makCard(treeSet);
        this.revalidate();
    }//GEN-LAST:event_btn_aMouseClicked

    private void btn_rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rechercheActionPerformed
        
        try {
            treeSet = Recuperer.etudiants(Main.database.getByFirstChar(table, str_recherche.getText(), "nom"));
            treeSet.addAll(Recuperer.etudiants(Main.database.getByFirstChar(table, str_recherche.getText(), "nce")));
            makCard(treeSet);
            this.revalidate();
        } catch (SQLException ex) {
            Logger.getLogger(Annuaire.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_rechercheActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualiser;
    private javax.swing.JButton btn_a;
    private javax.swing.JButton btn_b;
    private javax.swing.JButton btn_c;
    private javax.swing.JButton btn_d;
    private javax.swing.JButton btn_e;
    private javax.swing.JButton btn_f;
    private javax.swing.JButton btn_g;
    private javax.swing.JButton btn_h;
    private javax.swing.JButton btn_i;
    private javax.swing.JButton btn_j;
    private javax.swing.JButton btn_k;
    private javax.swing.JButton btn_l;
    private javax.swing.JButton btn_m;
    private javax.swing.JButton btn_n;
    private javax.swing.JButton btn_o;
    private javax.swing.JButton btn_p;
    private javax.swing.JButton btn_q;
    private javax.swing.JButton btn_r;
    private javax.swing.JButton btn_recherche;
    private javax.swing.JButton btn_s;
    private javax.swing.JButton btn_t;
    private javax.swing.JButton btn_u;
    private javax.swing.JButton btn_v;
    private javax.swing.JButton btn_w;
    private javax.swing.JButton btn_x;
    private javax.swing.JButton btn_y;
    private javax.swing.JButton btn_z;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton rechercheCible;
    private javax.swing.JTextField str_recherche;
    // End of variables declaration//GEN-END:variables

    
}
