/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package annuaire.panels;

import annuaire.personnes.Student;
import javax.swing.JPopupMenu;

/**
 *
 * @author mosco
 */
public class CardStudent extends javax.swing.JPanel {

    private Student student;
    /**
     * Creates new form Card
     * @param student
     */
    public CardStudent(Student student) {
        initComponents();
        this.student = student;
        nce.setText(student.getNce());
        nom.setText(student.getNom());
        prenoms.setText(student.getPrenoms());
        email.setText(student.getEmail());
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nom = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        prenoms = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nce = new javax.swing.JLabel();
        canvas = new java.awt.Canvas();
        plusInfo = new javax.swing.JButton();

        setBackground(java.awt.Color.darkGray);
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setForeground(java.awt.SystemColor.desktop);
        setMaximumSize(new java.awt.Dimension(200, 418));
        setMinimumSize(new java.awt.Dimension(200, 418));
        setPreferredSize(new java.awt.Dimension(200, 418));

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(java.awt.SystemColor.desktop);
        jPanel1.setMaximumSize(new java.awt.Dimension(200, 418));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 418));

        nom.setFont(new java.awt.Font("Ubuntu", 1, 25)); // NOI18N
        nom.setForeground(java.awt.Color.white);
        nom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nom.setText("nom");
        nom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        email.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        email.setForeground(java.awt.Color.white);
        email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email.setText("email");

        prenoms.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        prenoms.setForeground(java.awt.Color.white);
        prenoms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prenoms.setText("prenoms");

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("nce");

        nce.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        nce.setForeground(java.awt.Color.white);
        nce.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        canvas.setBackground(java.awt.Color.white);

        plusInfo.setBackground(java.awt.SystemColor.desktop);
        plusInfo.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        plusInfo.setForeground(java.awt.Color.white);
        plusInfo.setText("Plus d'information");
        plusInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addComponent(prenoms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(plusInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(nce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(prenoms, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plusInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void plusInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusInfoActionPerformed
        JPopupMenu jpm = new JPopupMenu();
        jpm.setLightWeightPopupEnabled(true);
        jpm.add(new CompletCardStudent(student));
        jpm.setLocation(100, 100);
        jpm.setVisible(true);
    }//GEN-LAST:event_plusInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nce;
    private javax.swing.JLabel nom;
    private javax.swing.JButton plusInfo;
    private javax.swing.JLabel prenoms;
    // End of variables declaration//GEN-END:variables
}
