/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package annuaire.panels;

import annuaire.Main;
import annuaire.Utils.MonControleur;
import annuaire.Utils.Recuperer;
import annuaire.msg.ErrorMsg;
import annuaire.msg.SuccesMsg;
import annuaire.personnes.Admin;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.NoSuchElementException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author mosco
 */
public class PanelConnexion extends javax.swing.JPanel {

    /**
     * Creates new form FrameConn
     */
    public PanelConnexion() {
        initComponents();
        setVisible(true);
        setFocusable(true);
        email.setFocusable(true);
        jPasswordField.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        connecter = new javax.swing.JButton();

        setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel1.setBackground(java.awt.SystemColor.controlDkShadow);
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Connectez-vous");

        email.setMinimumSize(new java.awt.Dimension(10, 50));
        email.setName("email"); // NOI18N
        email.setPreferredSize(new java.awt.Dimension(220, 25));

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Email");

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Password");

        jPasswordField.setPreferredSize(new java.awt.Dimension(220, 25));

        connecter.setBackground(java.awt.SystemColor.activeCaption);
        connecter.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        connecter.setForeground(java.awt.Color.white);
        connecter.setText("Se connecter");
        connecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                connecterMouseClicked(evt);
            }
        });
        connecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connecterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(connecter, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(connecter))
        );

        email.getAccessibleContext().setAccessibleName("email");
    }// </editor-fold>//GEN-END:initComponents

    private void connecterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connecterMouseClicked
        ResultSet resultSet;
        if(jPasswordField.getPassword() != null && jPasswordField.getPassword().length >= 6 && !email.getText().isEmpty() ){

            //Vérification du champ Email
            resultSet = Main.database.getByString(Admin.class.getSimpleName(), email.getName(), email.getText());
            if(resultSet != null){
                try {
                    Admin admin = (Admin) Recuperer.admins(resultSet).first();
                    if(String.valueOf(jPasswordField.getPassword()).equals(admin.getPassword())){
                        Main.admin = admin;
                        Main.addToPaneG(null);
                        Main.setIntojPanel();
                        new SuccesMsg();
                    }
                    else{
                        new ErrorMsg();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(PanelConnexion.class.getName()).log(Level.SEVERE, null, ex);
                }catch(NoSuchElementException e){
                    new ErrorMsg();
                }
                
            }
            else{
                new ErrorMsg();
            }
        
                
            
            
            //Vérification du mot de passe
        }
        else{
            new ErrorMsg("Veillez remplir tous les champs correctement !\n"
                    + "Entrez une addresse email valide !\n"
                    + "Le mot de passe doit être d'au moins 6 caractères !");
        }
            
    }//GEN-LAST:event_connecterMouseClicked

    private void connecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connecterActionPerformed
        SwingUtilities.invokeLater(new MonControleur());
    }//GEN-LAST:event_connecterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connecter;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField;
    // End of variables declaration//GEN-END:variables
}
