/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package annuaire;

import annuaire.DB.Database;
import annuaire.Utils.Recuperer;
import annuaire.menus.TypeOne;
import annuaire.panels.Annuaire;
import annuaire.personnes.Admin;
import annuaire.personnes.Student;
import annuaire.personnes.User;
import java.awt.BorderLayout;
import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mosco
 */
public class Main extends javax.swing.JDialog {

    private Annuaire annuaire;
    public static Database database = new Database();
    private static TreeSet<User> users;
    public static Admin admin;
    
    /**
     * Creates new form Prim
     * @param parent
     * @param modal
     */
    public Main(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        jMenuBar.add(new TypeOne());
        
        ResultSet resultSet = database.getAll(Student.class.getSimpleName());
        BorderLayout bl = new BorderLayout();
        jPanel.setLayout(bl);

        try {
            users = Recuperer.etudiants(resultSet);
            annuaire = new Annuaire(users);
            jPanel.add(annuaire);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }
    
    
    public static void addToPaneG(Component component){
        BorderLayout bl = new BorderLayout();
        jPanelG.removeAll();
        jPanelG.setLayout(bl);
        if(component != null){
            jPanelG.setSize(component.getSize());
            jPanelG.add(component);
            jSplitPane.setOneTouchExpandable(true);
            jSplitPane.setDividerLocation(0.4);
        } 
        
        jPanelG.revalidate();
        getjSplitPane().revalidate();
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel = new javax.swing.JPanel();
        jPanelG = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1119, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );

        jSplitPane.setRightComponent(jPanel);

        javax.swing.GroupLayout jPanelGLayout = new javax.swing.GroupLayout(jPanelG);
        jPanelG.setLayout(jPanelGLayout);
        jPanelGLayout.setHorizontalGroup(
            jPanelGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelGLayout.setVerticalGroup(
            jPanelGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );

        jSplitPane.setLeftComponent(jPanelG);

        jMenuBar.setBackground(java.awt.Color.black);
        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Main dialog = new Main(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            
            dialog.setVisible(true);
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JMenuBar jMenuBar;
    private static javax.swing.JPanel jPanel;
    private static javax.swing.JPanel jPanelG;
    private static javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables

    /**
     * @param jMenu
     */
    public static void setjMenuBar(javax.swing.JMenu jMenu) {
        jMenuBar.removeAll();
        jMenuBar.add(jMenu);
        jMenuBar.revalidate();
    }

    /**
     * @return the jSplitPane
     */
    public static javax.swing.JSplitPane getjSplitPane() {
        return jSplitPane;
    }



    /**
     * @param aAnnuaire the annuaire to set
     */
    public void setAnnuaire(Annuaire aAnnuaire) {
        annuaire = aAnnuaire;
        annuaire.validate();
        getjPanel().validate();
        getjPanel().validate();
    }

    /**
     * @return the annuaire
     */
    public Annuaire getAnnuaire() {
        return annuaire;
    }

    /**
     * @return the jPanel
     */
    public static javax.swing.JPanel getjPanel() {
        return jPanel;
    }

    /**
     * @param annuaire
     */
    public static void setIntojPanel(Annuaire annuaire) {
        BorderLayout bl = new BorderLayout();
        jPanel.removeAll();
        jPanel.setLayout(bl);
        jPanel.add(annuaire);
        jPanel.revalidate();
    }
    
    
    public static void setIntojPanel() {
        BorderLayout bl = new BorderLayout();
        jPanel.removeAll();
        jPanel.setLayout(bl);
        jPanel.add(new Annuaire(users));
        jPanel.revalidate();
    }
    
    
}
