/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package annuaire;

import annuaire.DB.Database;
import annuaire.frames.CardStudent;
import annuaire.personnes.Student;
import java.awt.GridLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mosco
 */
public class Main extends javax.swing.JDialog {
    
    GridLayout gridLayout = new GridLayout(0, 3, 5, 8);
    Database database = new Database();
    private final TreeSet treeSet = new TreeSet();
    private final String table = "etudiants";

    /**
     * Creates new form Main
     * @param parent
     * @param modal
     */
    public Main(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jPanel.setLayout(gridLayout);
        ResultSet resultSet = database.getAll("etudiants");
        makCard(sortedStudents(resultSet));
    }
    
    /*public ArrayList<Student> recherchePar(String nom){
        return database.getByChar(table, String.format("%s", nom), attr)
    }*/
    
    
    private void rechercherParNom(String searchChar){
        treeSet.clear();
        ResultSet resultSet = database.getByChar(table, searchChar, "nom");
        treeSet.addAll(sortedStudents(resultSet));
    }
    
    private void rechercheAvancer(String str){
        treeSet.clear();
        ResultSet resultSet = database.getByString(table, str, "nom");
        treeSet.addAll(sortedStudents(resultSet));
        ResultSet resultSet2 =  database.getByString(table, str, "prenoms");
        treeSet.addAll(sortedStudents(resultSet2));
    }
    private TreeSet<Student> sortedStudents(ResultSet resultSet){
        TreeSet<Student> students = new TreeSet<>();
        try {
            while(resultSet.next()) {
                String nce = resultSet.getString("nce");
                String nom = resultSet.getString("nom");
                String prenoms = resultSet.getString("prenoms");
                String date2naissance = resultSet.getString("date2naiss");
                String lieu2naissance = resultSet.getString("lieu2naiss");
                String email = resultSet.getString("email");
                String mobile = resultSet.getString("mobile");
                String niveau = resultSet.getString("niveau");
                Student student = new Student(nce, nom, prenoms, date2naissance, lieu2naissance, email, mobile, niveau);
                students.add(student);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        return students;
    }
    
    
    private void makCard(TreeSet<Student> students){
        jPanel.removeAll();
        Iterator<Student> iterator = students.iterator();
        while(iterator.hasNext()){
            CardStudent card = new CardStudent(iterator.next());
            jPanel.add(card);
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        str_recherche = new javax.swing.JTextField();
        btn_recherche = new javax.swing.JButton();
        btn_a = new javax.swing.JButton();
        btn_b = new javax.swing.JButton();
        btn_c = new javax.swing.JButton();
        btn_d = new javax.swing.JButton();
        btn_e = new javax.swing.JButton();
        btn_f = new javax.swing.JButton();
        btn_g = new javax.swing.JButton();
        btn_h = new javax.swing.JButton();
        btn_i = new javax.swing.JButton();
        btn_j = new javax.swing.JButton();
        btn_k = new javax.swing.JButton();
        btn_l = new javax.swing.JButton();
        btn_n = new javax.swing.JButton();
        btn_o = new javax.swing.JButton();
        btn_p = new javax.swing.JButton();
        btn_q = new javax.swing.JButton();
        btn_r = new javax.swing.JButton();
        btn_s = new javax.swing.JButton();
        btn_t = new javax.swing.JButton();
        btn_u = new javax.swing.JButton();
        btn_v = new javax.swing.JButton();
        btn_w = new javax.swing.JButton();
        btn_x = new javax.swing.JButton();
        btn_y = new javax.swing.JButton();
        btn_z = new javax.swing.JButton();
        btn_m = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        body = new javax.swing.JScrollPane();
        jPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setIconImage(null);

        jPanel1.setBackground(new java.awt.Color(231, 24, 24));

        btn_recherche.setText("rechercher");
        btn_recherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_rechercheMouseClicked(evt);
            }
        });

        btn_a.setText("A");
        btn_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aMouseClicked(evt);
            }
        });
        btn_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aActionPerformed(evt);
            }
        });
        btn_a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_aKeyPressed(evt);
            }
        });

        btn_b.setText("B");
        btn_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bMouseClicked(evt);
            }
        });

        btn_c.setText("C");
        btn_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cMouseClicked(evt);
            }
        });

        btn_d.setText("D");
        btn_d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dMouseClicked(evt);
            }
        });
        btn_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dActionPerformed(evt);
            }
        });

        btn_e.setText("E");
        btn_e.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eMouseClicked(evt);
            }
        });

        btn_f.setText("F");
        btn_f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_fMouseClicked(evt);
            }
        });

        btn_g.setText("G");
        btn_g.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_gMouseClicked(evt);
            }
        });

        btn_h.setText("H");
        btn_h.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hMouseClicked(evt);
            }
        });

        btn_i.setText("I");
        btn_i.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_iMouseClicked(evt);
            }
        });

        btn_j.setText("J");
        btn_j.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_jMouseClicked(evt);
            }
        });

        btn_k.setText("K");
        btn_k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kMouseClicked(evt);
            }
        });

        btn_l.setText("L");
        btn_l.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lMouseClicked(evt);
            }
        });

        btn_n.setText("N");
        btn_n.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nMouseClicked(evt);
            }
        });

        btn_o.setText("O");
        btn_o.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_oMouseClicked(evt);
            }
        });

        btn_p.setText("P");
        btn_p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pMouseClicked(evt);
            }
        });

        btn_q.setText("Q");
        btn_q.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_qMouseClicked(evt);
            }
        });

        btn_r.setText("R");
        btn_r.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_rMouseClicked(evt);
            }
        });

        btn_s.setText("S");
        btn_s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sMouseClicked(evt);
            }
        });

        btn_t.setText("T");
        btn_t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tMouseClicked(evt);
            }
        });

        btn_u.setText("U");
        btn_u.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_uMouseClicked(evt);
            }
        });

        btn_v.setText("V");
        btn_v.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vMouseClicked(evt);
            }
        });

        btn_w.setText("W");
        btn_w.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_wMouseClicked(evt);
            }
        });

        btn_x.setText("X");
        btn_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xMouseClicked(evt);
            }
        });

        btn_y.setText("Y");
        btn_y.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_yMouseClicked(evt);
            }
        });

        btn_z.setText("Z");
        btn_z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_zMouseClicked(evt);
            }
        });

        btn_m.setText("M");
        btn_m.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Groupe x");

        jLabel2.setText("design by");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(str_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_a)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_b)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_c)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_d)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_e)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_f)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_g)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_h)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_i)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_j)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_k)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_l)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_m)
                                .addGap(4, 4, 4)
                                .addComponent(btn_n)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_o)
                                .addGap(5, 5, 5)
                                .addComponent(btn_p)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_q)
                                .addGap(5, 5, 5)
                                .addComponent(btn_r)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_s)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_t)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_u)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_v)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_w)
                                .addGap(4, 4, 4)
                                .addComponent(btn_x)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_y)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_z)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_recherche)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(str_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_recherche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_a)
                    .addComponent(btn_b)
                    .addComponent(btn_c)
                    .addComponent(btn_d)
                    .addComponent(btn_e)
                    .addComponent(btn_f)
                    .addComponent(btn_g)
                    .addComponent(btn_h)
                    .addComponent(btn_i)
                    .addComponent(btn_j)
                    .addComponent(btn_k)
                    .addComponent(btn_l)
                    .addComponent(btn_n)
                    .addComponent(btn_o)
                    .addComponent(btn_p)
                    .addComponent(btn_q)
                    .addComponent(btn_r)
                    .addComponent(btn_s)
                    .addComponent(btn_t)
                    .addComponent(btn_u)
                    .addComponent(btn_v)
                    .addComponent(btn_w)
                    .addComponent(btn_x)
                    .addComponent(btn_y)
                    .addComponent(btn_z)
                    .addComponent(btn_m)))
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        body.setViewportView(jPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(body, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aActionPerformed

    private void btn_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dActionPerformed

    private void btn_aKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_aKeyPressed
        
    }//GEN-LAST:event_btn_aKeyPressed

    private void btn_aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aMouseClicked
        rechercherParNom(btn_a.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_aMouseClicked

    private void btn_rechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rechercheMouseClicked
        rechercheAvancer(str_recherche.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_rechercheMouseClicked

    private void btn_bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bMouseClicked
        rechercherParNom(btn_b.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_bMouseClicked

    private void btn_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cMouseClicked
       rechercherParNom(btn_c.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_cMouseClicked

    private void btn_dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dMouseClicked
        rechercherParNom(btn_d.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_dMouseClicked

    private void btn_eMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eMouseClicked
        rechercherParNom(btn_e.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_eMouseClicked

    private void btn_fMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fMouseClicked
        rechercherParNom(btn_f.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_fMouseClicked

    private void btn_gMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_gMouseClicked
        rechercherParNom(btn_g.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_gMouseClicked

    private void btn_hMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hMouseClicked
        rechercherParNom(btn_h.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_hMouseClicked

    private void btn_iMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_iMouseClicked
        rechercherParNom(btn_i.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_iMouseClicked

    private void btn_jMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jMouseClicked
       rechercherParNom(btn_j.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_jMouseClicked

    private void btn_kMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kMouseClicked
        rechercherParNom(btn_k.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_kMouseClicked

    private void btn_lMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lMouseClicked
        rechercherParNom(btn_l.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_lMouseClicked

    private void btn_mMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mMouseClicked
        rechercherParNom(btn_m.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_mMouseClicked

    private void btn_nMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nMouseClicked
        rechercherParNom(btn_n.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_nMouseClicked

    private void btn_oMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_oMouseClicked
       rechercherParNom(btn_o.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_oMouseClicked

    private void btn_pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pMouseClicked
        rechercherParNom(btn_p.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_pMouseClicked

    private void btn_qMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_qMouseClicked
       rechercherParNom(btn_q.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_qMouseClicked

    private void btn_rMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rMouseClicked
        rechercherParNom(btn_r.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_rMouseClicked

    private void btn_sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sMouseClicked
        rechercherParNom(btn_s.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_sMouseClicked

    private void btn_tMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tMouseClicked
        rechercherParNom(btn_t.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_tMouseClicked

    private void btn_uMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_uMouseClicked
       rechercherParNom(btn_u.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_uMouseClicked

    private void btn_vMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vMouseClicked
        rechercherParNom(btn_v.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_vMouseClicked

    private void btn_wMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_wMouseClicked
        rechercherParNom(btn_w.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_wMouseClicked

    private void btn_xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xMouseClicked
        rechercherParNom(btn_x.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_xMouseClicked

    private void btn_yMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yMouseClicked
        rechercherParNom(btn_y.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_yMouseClicked

    private void btn_zMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_zMouseClicked
        rechercherParNom(btn_z.getText());
        makCard(treeSet);
    }//GEN-LAST:event_btn_zMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane body;
    private javax.swing.JButton btn_a;
    private javax.swing.JButton btn_b;
    private javax.swing.JButton btn_c;
    private javax.swing.JButton btn_d;
    private javax.swing.JButton btn_e;
    private javax.swing.JButton btn_f;
    private javax.swing.JButton btn_g;
    private javax.swing.JButton btn_h;
    private javax.swing.JButton btn_i;
    private javax.swing.JButton btn_j;
    private javax.swing.JButton btn_k;
    private javax.swing.JButton btn_l;
    private javax.swing.JButton btn_m;
    private javax.swing.JButton btn_n;
    private javax.swing.JButton btn_o;
    private javax.swing.JButton btn_p;
    private javax.swing.JButton btn_q;
    private javax.swing.JButton btn_r;
    private javax.swing.JButton btn_recherche;
    private javax.swing.JButton btn_s;
    private javax.swing.JButton btn_t;
    private javax.swing.JButton btn_u;
    private javax.swing.JButton btn_v;
    private javax.swing.JButton btn_w;
    private javax.swing.JButton btn_x;
    private javax.swing.JButton btn_y;
    private javax.swing.JButton btn_z;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField str_recherche;
    // End of variables declaration//GEN-END:variables

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        @Override
        public void run() {
            Main dialog = new Main(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    }
}
