/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package annuaire.menus;

import annuaire.Main;
import annuaire.Utils.Recuperer;
import annuaire.panels.Annuaire;
import annuaire.panels.PanelStudent;
import annuaire.personnes.Student;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;

/**
 *
 * @author mosco
 */
public class MenuStudent extends javax.swing.JMenu {

    JMenuItem itemOne;
    JMenuItem itemTwo;
    /**
     * Creates new form TypeOne
     */
    public MenuStudent() {
        initComponents();
        
        setText("Mes étudiants");
        initJMenuItems();
        
        
    }
    
    //private void 
    
    private void initJMenuItems(){
        itemOne = new JMenuItem("Voir Liste étudiants");
        itemTwo = new JMenuItem("Ajouter étudiant");
        add(itemOne);
        add(itemTwo);
        
        itemOne.addActionListener(this::itemOneActionPerformed);
        itemTwo.addActionListener(this::itemTwoActionPerformed);
    }
    
    private void itemOneActionPerformed(java.awt.event.ActionEvent evt){
        try {
            Main.setIntojPanel(new Annuaire(Recuperer.etudiants(Main.database.getAll(Student.class.getSimpleName()))));
            Main.addToPaneG(null);
        } catch (SQLException ex) {
            Logger.getLogger(MenuStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void itemTwoActionPerformed(java.awt.event.ActionEvent evt){
        Main.addToPaneG(new PanelStudent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
