/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package annuaire.menus;

import annuaire.Main;
import annuaire.Utils.MonControleur;
import annuaire.panels.Card;
import javax.swing.JMenuItem;
import javax.swing.SwingUtilities;

/**
 *
 * @author mosco
 */
public class TypeTwo extends javax.swing.JMenu {

    JMenuItem itemOne;
    JMenuItem itemTwo;
    
    /**
     * Creates new form TypeOne
     */
    public TypeTwo() {
        initComponents();
        
        setText("Menu");
        initJMenuItems();
        
        
        
    }
    
    //private void 
    
    private void initJMenuItems(){
        itemOne = new JMenuItem("Mon Profil");
        itemTwo = new JMenuItem("Se Déconnecter");
        
        add(new MenuStudent());
        add(new MenuAdmin());
        add(itemOne);
        add(itemTwo);
        
        itemOne.addActionListener(this::itemOneActionPerformed);
        itemTwo.addActionListener(this::itemTwoActionPerformed);
    }
    
    
    
    private void itemOneActionPerformed(java.awt.event.ActionEvent evt){
        Main.addToPaneG(new Card(Main.admin));
    }
    
    private void itemTwoActionPerformed(java.awt.event.ActionEvent evt){
        Main.addToPaneG(null);
        Main.admin = null;
        Main.setIntojPanel();
        SwingUtilities.invokeLater(new MonControleur());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
